### ISSUE TITLE
Receiving down for me

### ISSUE THREAD

**Issue by jeremycherfas** [voxpelli/webpage-webmentions#205]
Hello

I got a series of alerts from Zapier, where I have a feed that sends an email based on new items in an RSS feed.

The error is:
```
Trigger partner failure: The app returned "500 Server Error: Internal Server Error for url: https://webmention.herokuapp.com/api/mentions?site=jeremycherfas.net&amp;format=html ; {&#34;error&#34;:&#34;An error occurred&#34;}".
```

The RSS feed is located at `https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fwebmention.herokuapp.com%2Fapi%2Fmentions%3Fsite%3Djeremycherfas.net%26format%3Dhtml`

I don't know whether the API has changed, or something else. I just tried sending myself web mentions from a variety of sources, but they do not seem to have been received. 

https://indiewebify.me/send-webmentions/ reported they had been successfully sent.

https://telegraph.p3k.io/webmention/18b0cVmNY7lmtO9gSD/details reported that they were Accepted but "The webmention endpoint did not return a status URL"

If there is any further information I can provide I will try to do so.

Thanks

Jeremy Cherfas

**Comment by voxpelli** [comment]
This is the error I'm getting in the backend:

```
Error: Invalid URL, should be an absolute one (tag:indieweb.social:112331285963196700/,2013)
  at normalizeUrlRaw (/app/lib/utils/url-tools.js:28:11)
  at normalizeUrl (/app/lib/utils/url-tools.js:53:58)
  at /app/lib/classes/entries.js:88:36
  at Array.map (<anonymous>)
  at Entries._resolveDerivedData (/app/lib/classes/entries.js:88:25)
  at Entries._distillMention (/app/lib/classes/entries.js:117:15)
  at /app/lib/classes/entries.js:301:26
  at Array.map (<anonymous>)
  at /app/lib/classes/entries.js:301:10
```

So somehow an invalid URL has snuck itself into the list of mentions for you :/

**Comment by voxpelli** [comment]
For my own context: It was a `in-reply-to` in the parsed microformat + showed as a `hrefs`

I will manually fix it

**Comment by voxpelli** [comment]
@jeremycherfas Fixed it manually for you, its back up and working: https://webmention.herokuapp.com/api/mentions?site=jeremycherfas.net&format=html

**Comment by jeremycherfas** [comment]
Thanks Pelle

Was this peculiar to one sender? Maybe I should let them know.

Jeremy

**Comment by voxpelli** [comment]
@jeremycherfas It was a bridgy federated mastodon post that no longer exists, it should be dealt with by me

**Comment by jeremycherfas** [comment]
OK. Thanks. And thanks for everything you do to enable me to receive web mentions.

**Comment by jeremycherfas** [comment]
Apologies, but getting the same error again from Zapier.

`Trigger partner failure: The app returned "500 Server Error: Internal Server Error for url: https://webmention.herokuapp.com/api/mentions?site=jeremycherfas.net&amp;format=html ; {&#34;error&#34;:&#34;An error occurred&#34;}".`

**Comment by voxpelli** [comment]
@jeremycherfas I'll fix in a bit

**Comment by voxpelli** [comment]
@jeremycherfas I used the query from https://github.com/voxpelli/webpage-webmentions/issues/208#issuecomment-2165109424 and removed these two mentions to make it work again:

* http://brid.gy/comment/mastodon/@etp@indieweb.social/113011947663705214/113011966770578657/ - https://socks.masto.host/@John/113011966761318907
* http://brid.gy/comment/mastodon/@etp@indieweb.social/112976879295779281/112984854224364021/ - https://mastodon.social/@rscottjones/112984854170625166

I really hope I can get some time to fix this error soon, but keep pinging me until then!

**Comment by jeremycherfas** [comment]
Many thanks Pelle.

I will restart my Zapier.

Jeremy
