### ISSUE TITLE
Node 6.x

### ISSUE THREAD

**Issue by dustinboston** [voxpelli/webpage-webmentions#33]
I was just trying to set this up on my server when I realized that it wanted iojs 3.x. I was just wondering if you had any plans to update it to use node 6. Thanks!

**Comment by voxpelli** [comment]
Working on this now and tracking it in #34

**Comment by voxpelli** [comment]
Master should now work on Node 6.x and 5.x and actually requires `>=5.0.0` now

**Comment by dustinboston** [comment]
Yay! Thanks! I'll give it a shot!
