### ISSUE TITLE
Ensure target and source can't be the same page

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/webpage-webmentions#43]
As that's apparently possible currently: https://voxpelli.com/2016/07/better-handle-npm-modules/

**Comment by frankmeeuwsen** [comment]
I currently experience this problem with the hosted endpoint on https://webmention.herokuapp.com/. Since the spec [states](https://www.w3.org/TR/webmention/#request-verification): "The receiver MUST reject the request if the source URL is the same as the target URL.", are you planning to make an exception when source and target are identical?

**Comment by voxpelli** [comment]
This should absolutely be fixed, I just haven’t had a lot of time lately to put into this project and there are some more pressing issues 🙂

**Comment by frankmeeuwsen** [comment]
I understand. Is there anything I can do myself to delete the webmentions? I can't seem to find anything in the documentation.

**Comment by voxpelli** [comment]
Currently, no, it’s tracked in https://github.com/voxpelli/webpage-webmentions/issues/28

If you give me a list of comments you want to have removed then I can maybe try deleting them straight from the database. You can list them here or mail me at pelle@kodfabrik.se

**Comment by frankmeeuwsen** [comment]
Actually it's all comments from the domain https://diggingthedigital.com/ and https://webmention.rocks. Thanks!

**Comment by voxpelli** [comment]
@frankmeeuwsen ok, any of those comments that are specific to the issue here?

**Comment by frankmeeuwsen** [comment]
@voxpelli I'll take a look in the JSON from the site and let you know in a while. Thanks for your help so far!

**Comment by voxpelli** [comment]
@frankmeeuwsen I found some spare time, and the nudge from @sknebel helped getting me going, so now this is implemented and launched as `0.12.6`: https://github.com/voxpelli/webpage-webmentions/releases/tag/v0.12.6 😄 

I haven't filtered out the old mentions yet, that would be a follow up to this, and since its getting late here + that deletes has a tendency to go somewhat wrong when done in a hurry, I will have to wait with that.

But please do nudge me whenever you remember that it hasn't been done, and I get reminded as well 😜 

![](https://media.giphy.com/media/BsQAVgY6ksvIY/giphy.gif)

**Comment by frankmeeuwsen** [comment]
No worries, I appreciate the time and effort that you and @sknebel have taken already. I'll ping myself in a while to check the old mentions. I haven't taken a look at the JSON myself either to make a correct list. Sometimes a mention to an older post is actually useful as a way to direct readers to follow-up post etc. So I'll take a look as well.
